---
name: Merge Gatekeeper

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go tip
        run: |
          echo ${{ github.event.pull_request.head.sha || github.event.push.head.sha }}
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.event.push.head.sha }}
          echo ${{ github.event.push.sha }}
          echo ${{ github.sha }}

      - name: pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo pull_request

      - name: push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo push

  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Run Merge Gatekeeper
        uses: percona-platform/merge-gatekeeper@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}