---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go tip
        run: |
          echo ${{ github.event.pull_request.head.sha || github.event.push.head.sha }}

  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.event.push.head.sha }}
